troke:
  upload-path: uploads-prod
spring:
  datasource:
    url: jdbc:postgresql://ec2-44-193-178-122.compute-1.amazonaws.com:5432/d8f2km4phgjchb
    driver-class-name: org.postgresql.Driver
    username: zzydqcgbwlbqkx
    password: cf79849361eca3249e9ebc1e799ac77f6fed1cee4be42076b4f151d6cfdafd43
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      javax:
        persistence:
          validation:
            mode: none
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mail:
    host: smtp.gmail.com
    username: toannguyenitit@gmail.com
    password: fsbdmklfavtrybpl
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true