spring:
  profiles:
    active:
    - prod
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
---
spring:
  h2:
    console:
      enabled: false
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:h2:./troke-prod
  jpa:
    hibernate:
      ddl-auto: update
troke:
  upload-path: uploads-prod
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:troke-dev
troke:
  upload-path: uploads-dev
---
spring:
  config:
    activate:
      on-profile: test
troke:
  upload-path: uploads-test